#cloud-config

coreos:
  update:
    reboot-strategy: off
  units:
    - name: oam-server-api.service
      command: start
      content: |
        [Unit]
        Description=OpenAerialMap Server API
        After=docker.service

        [Service]
        Restart=always

        ExecStartPre=-/usr/bin/docker kill oam-server-api
        ExecStartPre=-/usr/bin/docker rm -f oam-server-api
        ExecStartPre=/usr/bin/docker pull quay.io/hotosm/oam-server-api:latest
        ExecStart=/usr/bin/docker run --name oam-server-api -p 80:8000 quay.io/hotosm/oam-server-api:latest start
        ExecStop=/usr/bin/docker stop -t 2 oam-server-api

    - name: oam-server-activity-metrics-publisher.service
      content: |
        [Unit]
        Description=OpenAerialMap Server Activity Metrics Publisher
        After=install-jq.service

        [Service]
        Environment="SWF_DOMAIN=test"
        Environment="SWF_TASK_LIST=test"
        Type=oneshot
        ExecStart=/bin/sh -c '/usr/bin/docker run --rm -e AWS_DEFAULT_REGION=us-west-2 quay.io/azavea/aws-cli:0.1.0 \
            cloudwatch \
            put-metric-data \
            --metric-name PendingActivityTasks \
            --namespace OAMServer \
            --value "$(/usr/bin/docker run --rm -e AWS_DEFAULT_REGION=us-west-2 quay.io/azavea/aws-cli:0.1.0 \
                swf \
                count-pending-activity-tasks \
                --domain ${SWF_DOMAIN} \
                --task-list name=${SWF_TASK_LIST} | jq .count)" \
            --timestamp "$(date -u -Iseconds)"'

    - name: oam-server-activity-metrics-publisher.timer
      command: start
      content: |
        [Unit]
        Description=Runs OpenAerialMap Server Activity Metrics Publisher every 5 minutes

        [Timer]
        OnBootSec=120
        OnCalendar=*:0/5

    - name: oam-server-decision-metrics-publisher.service
      content: |
        [Unit]
        Description=OpenAerialMap Server Decision Metrics Publisher
        After=install-jq.service

        [Service]
        Environment="SWF_DOMAIN=test"
        Environment="SWF_TASK_LIST=test"
        Type=oneshot
        ExecStart=/bin/sh -c '/usr/bin/docker run --rm -e AWS_DEFAULT_REGION=us-west-2 quay.io/azavea/aws-cli:0.1.0 \
            cloudwatch \
            put-metric-data \
            --metric-name PendingDecisionTasks \
            --namespace OAMServer \
            --value "$(/usr/bin/docker run --rm -e AWS_DEFAULT_REGION=us-west-2 quay.io/azavea/aws-cli:0.1.0 \
                swf \
                count-pending-decision-tasks \
                --domain ${SWF_DOMAIN} \
                --task-list name=${SWF_TASK_LIST} | jq .count)" \
            --timestamp "$(date -u -Iseconds)"'

    - name: oam-server-decision-metrics-publisher.timer
      command: start
      content: |
        [Unit]
        Description=Runs OpenAerialMap Server Decision Metrics Publisher every 5 minutes

        [Timer]
        OnBootSec=120
        OnCalendar=*:0/5

    - name: install-jq.service
      command: start
      content: |
        [Unit]
        Description=Install the jq command line utility

        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/wget -o /opt/bin/jq "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
